"""Tests for registered glitch populations and the ``et-o3-anchored-v1`` preset.

Three separable things are pinned here.

**The anchors.** Every registered rate, tail index, truncation and frequency edge is a
measurement over two published data products, summarized in
``src/gwmock_noise/data/glitch_population/o3_reference_summary.json`` and regenerated by
``scripts/measure_glitch_population_anchors.py``. The tests assert the constants against
that summary through the same functions the harness measures with, so a constant edited by
hand -- or a summary regenerated against a different selection -- fails here rather than
quietly changing what a campaign injects.

**The pinning machinery.** A population serializes, round-trips, and digests; the digest
moves when anything registered moves, and does not move otherwise. A campaign that pins a
digest is relying on both halves of that.

**The pairing.** Arms of a paired comparison have to inject the identical glitch
realization. The realization is therefore asserted to be independent of the base noise, of
the interferometer list, and of whether it was generated in one call or streamed.
"""

from __future__ import annotations

import json
from dataclasses import replace

import numpy as np
import pytest
from measure_glitch_population_anchors import (
    CONFIDENCE_MINIMUM,
    SNR_MINIMUM,
    expected_hill_of_truncated_draws,
    hill_index,
    report,
    round_outward,
    truncated_pareto_index,
)

from gwmock_noise.data.glitch_population import load_o3_reference_summary
from gwmock_noise.glitches import BlipGlitch, LogNormalAmplitudeDistribution, NetworkCoherence
from gwmock_noise.glitches.snr import PowerLawSNRDistribution, snr_survival
from gwmock_noise.populations import (
    GLITCH_POPULATION_SCHEMA_VERSION,
    GlitchClass,
    GlitchPopulation,
    available_glitch_populations,
    et_o3_anchored_population,
    get_glitch_population,
)
from gwmock_noise.populations import et_o3_anchored as anchors
from gwmock_noise.simulators import ColoredNoiseSimulator

#: The registered population's digest. A campaign pins this, so it is pinned here too: a
#: change to any registered quantity moves it, and moving it is a deliberate act that
#: belongs in the same commit as the change and in the anchor page's record.
REGISTERED_DIGEST = "sha256:58fb23aef4b4dd0d0038ebdae09da51bdaf638821aca0df97ead74dcbc1dc3b0"

#: Sampling frequency the registered population needs. Its short class is supported up to
#: 780 Hz, so anything below 1560 Hz cannot represent it and is refused rather than
#: narrowed.
SAMPLING_FREQUENCY = 2048.0


@pytest.fixture(name="summary")
def _summary() -> dict:
    """The bundled measurement the registered constants are asserted against."""
    return load_o3_reference_summary()


@pytest.fixture(name="population")
def _population() -> GlitchPopulation:
    """The registered population, as a campaign would resolve it."""
    return get_glitch_population(anchors.POPULATION_NAME)


def _busy_population(**overrides: float) -> GlitchPopulation:
    """The registered population with both rates raised, so short tests see events.

    Rates are the one registered quantity a test may move without changing what is being
    tested: everything else -- the morphologies, the amplitude laws, the coherence -- is
    the registered one. Raising them is what lets a few seconds of generated data stand in
    for the hours a campaign runs.
    """
    return et_o3_anchored_population(short_rate_hz=0.5, coherent_rate_hz=0.5, **overrides)


# ---------------------------------------------------------------------------------------
# The anchors
# ---------------------------------------------------------------------------------------


def test_the_bundled_summary_is_internally_consistent(summary: dict) -> None:
    """Each class's rate is its count over the livetime it was counted in.

    The summary is generated, so this is not testing arithmetic -- it is testing that the
    file in the tree was generated by the harness in the tree, against the selection the
    harness declares. A summary hand-edited to move a rate fails here.
    """
    assert summary["selection"] == {"snr_minimum": SNR_MINIMUM, "confidence_minimum": CONFIDENCE_MINIMUM}
    livetime = summary["livetime_seconds"]
    assert livetime["pooled"] == pytest.approx(livetime["H1"] + livetime["L1"])
    for block in summary["classes"].values():
        for key in ("H1", "L1", "pooled"):
            assert block["rate_hz"][key] == pytest.approx(block["counts"][key] / livetime[key], rel=1e-12)
        assert block["counts"]["pooled"] == block["counts"]["H1"] + block["counts"]["L1"]


@pytest.mark.parametrize(
    ("registered", "measured_class"),
    [
        (anchors.SHORT_RATE_HZ, "Blip"),
        (anchors.COHERENT_RATE_HZ, "Scattered_Light"),
    ],
)
def test_registered_rates_are_the_measured_pooled_rates(summary: dict, registered: float, measured_class: str) -> None:
    """To the five significant figures the constants are written to."""
    measured = summary["classes"][measured_class]["rate_hz"]["pooled"]
    assert registered == pytest.approx(measured, rel=1e-4)


@pytest.mark.parametrize(
    ("registered", "measured_class"),
    [
        (anchors.SHORT_SNR_ALPHA, "Blip"),
        (anchors.COHERENT_SNR_ALPHA, "Scattered_Light"),
    ],
)
def test_registered_tail_indices_are_the_truncated_maximum_likelihood_exponents(
    summary: dict, registered: float, measured_class: str
) -> None:
    """And deliberately not the Hill indices, which would be the natural mistake."""
    block = summary["classes"][measured_class]["snr"]
    assert registered == pytest.approx(block["truncated_pareto_alpha"], abs=5e-5)
    assert registered != pytest.approx(block["hill_alpha"], abs=5e-3)


@pytest.mark.parametrize(
    ("registered", "measured_class"),
    [
        (anchors.SHORT_SNR_ALPHA, "Blip"),
        (anchors.COHERENT_SNR_ALPHA, "Scattered_Light"),
    ],
)
def test_the_registered_law_reproduces_the_measured_tail_index(
    summary: dict, registered: float, measured_class: str
) -> None:
    """The check that made the exponent what it is, and the reason it is not the Hill index.

    The amplitude law a campaign injects is a power law *truncated* at the largest SNR the
    reference sample contains. A truncated law drawn with the Hill index of that sample
    produces a sample whose own Hill index is steeper -- 1.4149 against a measured 1.3763
    for the short class -- so the registered population would have injected a measurably
    lighter tail than the one it was anchored to, and nothing in the configuration would
    have said so. The exponent is therefore estimated under the truncated model, and what
    is asserted here is the property that motivates it: the law's own draws recover the
    measurement.
    """
    block = summary["classes"][measured_class]["snr"]
    reproduced = expected_hill_of_truncated_draws(anchors.REFERENCE_SNR_THRESHOLD, registered, block["maximum"])
    assert reproduced == pytest.approx(block["hill_alpha"], rel=1e-3)
    # The summary's own figure, computed from the unrounded estimate rather than from the
    # four-decimal constant the population registers -- hence a tolerance, not equality.
    assert block["hill_of_truncated_draws"] == pytest.approx(reproduced, rel=1e-4)

    # The naive choice, and the size of the error it would have carried.
    naive = expected_hill_of_truncated_draws(anchors.REFERENCE_SNR_THRESHOLD, block["hill_alpha"], block["maximum"])
    assert naive > block["hill_alpha"] * 1.005


def test_the_truncated_estimator_recovers_an_exponent_it_is_given() -> None:
    """The estimator the registered exponents rest on, against a law of known index."""
    minimum, maximum, truth = 7.5, 344.38, 1.3333
    rng = np.random.default_rng(31337)
    law = PowerLawSNRDistribution(minimum=minimum, alpha=truth, maximum=maximum)
    sample = np.array([law.sample(rng) for _ in range(200_000)])

    assert truncated_pareto_index(sample, minimum, maximum) == pytest.approx(truth, rel=5e-3)
    # And the sample's Hill index is the steeper number the closed form predicts, which is
    # the whole reason the two estimators are not interchangeable.
    assert hill_index(sample, minimum)[0] == pytest.approx(
        expected_hill_of_truncated_draws(minimum, truth, maximum), rel=5e-3
    )


def test_the_measurement_harness_reports_the_bundled_summary(summary: dict, capsys: pytest.CaptureFixture[str]) -> None:
    """The harness's own printout, over the shape it ships.

    Its report path takes a few minutes of downloads to reach in anger, so a formatting
    slip there is found by nobody until someone re-measures. The bundled summary has the
    shape the harness writes, so it is the fixture that closes that gap.
    """
    report(summary)
    printed = capsys.readouterr().out
    assert "truncated-Pareto MLE (registered)" in printed
    assert "Observing time" in printed
    for name in summary["classes"]:
        assert f"== {name} ==" in printed


@pytest.mark.parametrize(
    ("registered", "measured_class"),
    [
        (anchors.SHORT_SNR_MAXIMUM, "Blip"),
        (anchors.COHERENT_SNR_MAXIMUM, "Scattered_Light"),
    ],
)
def test_registered_truncations_are_the_largest_observed_snr(
    summary: dict, registered: float, measured_class: str
) -> None:
    """The loud tail is cut where the reference sample stops, not at a round number."""
    assert registered == pytest.approx(summary["classes"][measured_class]["snr"]["maximum"], abs=5e-3)


def test_the_short_class_band_is_the_rounded_peak_frequency_percentiles(summary: dict) -> None:
    """Applied through the harness's own rounding rule, not restated here."""
    percentiles = summary["classes"]["Blip"]["peak_frequency_hz"]["percentiles"]
    assert round_outward(percentiles["p1"], upward=False) == anchors.SHORT_LOW_FREQUENCY_HZ
    assert round_outward(percentiles["p99"], upward=True) == anchors.SHORT_HIGH_FREQUENCY_HZ


def test_the_coherent_class_duration_and_apex_are_the_measured_medians(summary: dict) -> None:
    """Its band, by contrast, is published rather than measured -- see the anchor page."""
    block = summary["classes"]["Scattered_Light"]
    assert pytest.approx(block["duration_seconds"]["median"]) == anchors.COHERENT_DURATION_SECONDS
    assert pytest.approx(block["peak_frequency_hz"]["median"], abs=0.05) == anchors.COHERENT_PEAK_FREQUENCY_HZ
    # The measured apex sits comfortably inside the published shelf band, which is the
    # consistency check between the two different kinds of anchor the class uses.
    assert block["peak_frequency_hz"]["percentiles"]["p1"] > anchors.COHERENT_LOW_FREQUENCY_HZ
    assert block["peak_frequency_hz"]["percentiles"]["p99"] < anchors.COHERENT_HIGH_FREQUENCY_HZ


def test_the_hill_estimator_recovers_an_index_it_is_given() -> None:
    """The estimator the anchors rest on, checked against a distribution of known index.

    An anchor is only as good as the estimator that produced it, and ``hill_index`` is
    used by nothing else in the tree, so nothing else would catch it being wrong by a
    factor of the log base or by one.
    """
    rng = np.random.default_rng(20260919)
    truth = 1.4
    sample = 7.5 * (1.0 - rng.random(200_000)) ** (-1.0 / truth)
    estimate, stderr, count = hill_index(sample, 7.5)
    assert count == sample.size
    assert estimate == pytest.approx(truth, abs=5.0 * stderr)


def test_the_population_carries_its_references_and_its_unanchored_quantities(
    population: GlitchPopulation,
) -> None:
    """A consumer reading a pinned population reads the caveats with it."""
    assert len(population.references) >= 4
    assert any("arXiv:1901.05093" in reference for reference in population.references)
    assert any("zenodo.5649212" in reference for reference in population.references)
    joined = " ".join(population.unanchored)
    assert "participation probability" in joined
    assert "coherent across a network" in joined
    assert "Poisson" in joined


# ---------------------------------------------------------------------------------------
# Serialization and the digest
# ---------------------------------------------------------------------------------------


def test_the_population_round_trips_through_its_serialization(population: GlitchPopulation) -> None:
    """A manifest can carry the definition and rebuild exactly it."""
    payload = json.loads(json.dumps(population.serialize()))
    rebuilt = GlitchPopulation.deserialize(payload)

    assert rebuilt.serialize() == population.serialize()
    assert rebuilt.digest() == population.digest()
    assert rebuilt.classes[1].model.network == NetworkCoherence(
        participation_probability=anchors.COHERENT_PARTICIPATION_PROBABILITY,
        amplitude_ratio_std=anchors.COHERENT_AMPLITUDE_RATIO_STD,
    )


def test_the_registered_digest_is_the_one_campaigns_pin(population: GlitchPopulation) -> None:
    """Pinned deliberately.

    Updating this literal is the act of saying that what the registered population injects
    has changed. If this fails and the change was intended, the anchor page's record of the
    digest has to move with it.
    """
    assert population.digest() == REGISTERED_DIGEST
    assert get_glitch_population(anchors.POPULATION_NAME).digest() == REGISTERED_DIGEST


def test_the_digest_travels_because_the_psd_is_named_not_pathed(population: GlitchPopulation) -> None:
    """An absolute path in the serialization would make the digest machine-dependent."""
    payload = population.serialize()
    for entry in payload["classes"]:
        psd_file = entry["model"]["psd_file"]
        assert psd_file == anchors.DEFAULT_PSD
        assert not psd_file.startswith("/")


@pytest.mark.parametrize(
    "overrides",
    [
        {"short_rate_hz": anchors.SHORT_RATE_HZ * 1.000001},
        {"coherent_rate_hz": anchors.COHERENT_RATE_HZ * 2.0},
        {"participation_probability": 0.5},
        {"amplitude_ratio_std": 0.1},
    ],
)
def test_weakening_an_unanchored_assumption_changes_the_digest(overrides: dict) -> None:
    """A run cannot claim the registered population while having varied it."""
    assert et_o3_anchored_population(**overrides).digest() != REGISTERED_DIGEST


def test_rewriting_what_a_class_means_changes_the_digest(population: GlitchPopulation) -> None:
    """The prose is part of the registered definition, deliberately.

    A population whose numbers are untouched but whose description now claims something
    else is a different population, and a digest that did not move would say otherwise.
    """
    reworded = replace(
        population,
        classes=(replace(population.classes[0], description="Something else entirely."), *population.classes[1:]),
    )
    assert reworded.digest() != population.digest()


def test_the_canonical_form_is_sorted_and_compact(population: GlitchPopulation) -> None:
    """Two processes have to render it identically for a digest to mean anything."""
    canonical = population.canonical_json()
    assert canonical == json.dumps(json.loads(canonical), sort_keys=True, separators=(",", ":"))
    assert " " not in canonical[: canonical.index('"classes"')]


def test_an_unreadable_schema_version_is_refused(population: GlitchPopulation) -> None:
    """A future manifest fails loudly rather than being read with today's meanings."""
    payload = population.serialize() | {"schema_version": "9.0.0"}
    with pytest.raises(ValueError, match="schema version"):
        GlitchPopulation.deserialize(payload)


def test_the_registry_lists_the_population_and_names_it_in_an_error() -> None:
    """A typo is the likeliest cause of a miss, so the message has to say what to type."""
    assert anchors.POPULATION_NAME in available_glitch_populations()
    with pytest.raises(KeyError, match=anchors.POPULATION_NAME):
        get_glitch_population("et-o3-anchored-v2")


def test_a_population_refuses_to_be_empty_or_ambiguous(population: GlitchPopulation) -> None:
    """Zero classes, and two classes under one name."""
    with pytest.raises(ValueError, match="at least one class"):
        GlitchPopulation(name="empty", description="nothing", classes=())
    with pytest.raises(ValueError, match="class names repeat"):
        GlitchPopulation(
            name="twice",
            description="one name, two meanings",
            classes=(population.classes[0], replace(population.classes[1], name=population.classes[0].name)),
        )


def test_a_class_refuses_a_blank_field(population: GlitchPopulation) -> None:
    """Every prose field is in the digest, so a blank one is a blank in the record."""
    with pytest.raises(ValueError, match="morphology"):
        GlitchClass(name="x", morphology="   ", description="y", model=population.models()[0])


# ---------------------------------------------------------------------------------------
# The expected-count decomposition
# ---------------------------------------------------------------------------------------


def test_the_expected_count_is_the_product_of_the_factors_it_reports(population: GlitchPopulation) -> None:
    """The decomposition is not a commentary on the total; it is the total."""
    rows = population.expected_counts(livetime_seconds=2048.0, detectors=["E1", "E2", "E3"], snr_threshold=10.0)
    assert len(rows) == 6
    for row in rows:
        assert row.expected == pytest.approx(
            row.rate_hz * row.livetime_seconds * row.participation * row.selection, rel=1e-12
        )
        assert row.network_events == pytest.approx(row.expected / row.participation, rel=1e-12)


def test_the_selection_factor_is_the_survival_of_the_registered_amplitude_law(
    population: GlitchPopulation,
) -> None:
    """Read off the distribution in closed form, not estimated from a realization."""
    rows = population.expected_counts(livetime_seconds=1.0, detectors=["E1"], snr_threshold=20.0)
    for row in rows:
        model = population.model_for(row.glitch_class)
        assert row.selection == pytest.approx(snr_survival(model.snr, 20.0))
    assert all(0.0 < row.selection < 1.0 for row in rows)

    unfiltered = population.expected_counts(livetime_seconds=1.0, detectors=["E1"])
    assert all(row.selection == 1.0 for row in unfiltered)


def test_participation_enters_the_per_channel_count_but_not_the_network_count() -> None:
    """Halving the participation halves what a channel sees and leaves the network alone."""
    full = et_o3_anchored_population()
    half = et_o3_anchored_population(participation_probability=0.5)

    def coherent_row(candidate: GlitchPopulation) -> object:
        return next(
            row
            for row in candidate.expected_counts(livetime_seconds=3600.0, detectors=["E1", "E2"])
            if row.glitch_class == "network_coherent" and row.detector == "E1"
        )

    one, other = coherent_row(full), coherent_row(half)
    assert other.expected == pytest.approx(0.5 * one.expected)
    assert other.network_events == pytest.approx(one.network_events)


def test_the_registered_counts_are_what_a_realization_produces() -> None:
    """The decomposition against the generator, which is the check that matters.

    A rate that is per-channel where the code treats it as per-network, or a participation
    factor applied twice, changes the total by a factor nothing else in the suite would
    notice. The population here is the registered one with its two rates raised, so a few
    hundred seconds of data carries enough events for a Poisson comparison to bite.
    """
    detectors = ["E1", "E2", "E3"]
    livetime = 400.0
    busy = _busy_population()
    realization = busy.realize(detectors=detectors, duration=livetime, sampling_frequency=SAMPLING_FREQUENCY, seed=11)

    expectation = {
        (row.glitch_class, row.detector): row.expected
        for row in busy.expected_counts(livetime_seconds=livetime, detectors=detectors)
    }
    kinds = {"short_single_channel": "blip", "network_coherent": "scattered_light"}
    for (glitch_class, detector), expected in expectation.items():
        observed = sum(
            1 for event in realization.events if event["detector"] == detector and event["kind"] == kinds[glitch_class]
        )
        assert abs(observed - expected) < 4.0 * np.sqrt(expected), (
            f"{glitch_class} in {detector}: expected {expected:.1f}, observed {observed}"
        )


@pytest.mark.parametrize(
    ("livetime", "detectors", "match"),
    [
        (0.0, ["E1"], "livetime_seconds"),
        (-1.0, ["E1"], "livetime_seconds"),
        (1.0, [], "at least one interferometer"),
    ],
)
def test_expected_counts_refuses_an_impossible_request(
    population: GlitchPopulation, livetime: float, detectors: list[str], match: str
) -> None:
    """A zero or negative livetime, and no interferometers at all."""
    with pytest.raises(ValueError, match=match):
        population.expected_counts(livetime_seconds=livetime, detectors=detectors)


def test_a_population_that_does_not_cover_an_interferometer_is_refused() -> None:
    """Both when counting and when realizing, because both would be silently wrong."""
    scoped = et_o3_anchored_population()
    scoped = replace(
        scoped,
        classes=tuple(replace(entry, model=replace_detectors(entry.model, ["E1"])) for entry in scoped.classes),
    )
    with pytest.raises(ValueError, match="no glitch model applies to E2"):
        scoped.expected_counts(livetime_seconds=1.0, detectors=["E1", "E2"])
    with pytest.raises(ValueError, match="no glitch model applies to E2"):
        scoped.realize(detectors=["E1", "E2"], duration=1.0, sampling_frequency=SAMPLING_FREQUENCY, seed=1)


def replace_detectors(model: BlipGlitch, detectors: list[str]) -> BlipGlitch:
    """Rebuild one model scoped to ``detectors``.

    The models are slotted dataclasses with init-only ``kind`` fields, so a scoped copy is
    made by round-tripping the serialization rather than by ``dataclasses.replace``.
    """
    from gwmock_noise.glitches.models import normalize_glitch_models

    (rebuilt,) = normalize_glitch_models([model.serialize() | {"detectors": detectors}])
    return rebuilt


# ---------------------------------------------------------------------------------------
# The realization, and the pairing it makes possible
# ---------------------------------------------------------------------------------------


def test_the_realization_is_reproducible_for_a_fixed_seed() -> None:
    """Two calls, two populations resolved separately, one array."""
    first = _busy_population().realize(
        detectors=["E1", "E2"], duration=64.0, sampling_frequency=SAMPLING_FREQUENCY, seed=2026
    )
    second = _busy_population().realize(
        detectors=["E1", "E2"], duration=64.0, sampling_frequency=SAMPLING_FREQUENCY, seed=2026
    )

    assert first.events, "the fixture must fire events for this to say anything."
    for detector in ("E1", "E2"):
        assert np.array_equal(first.strain[detector], second.strain[detector])
    assert first.events == second.events
    assert first.stamp == second.stamp


def test_a_different_seed_gives_a_different_realization() -> None:
    """The contrast case, so the reproducibility test is not passing on a constant."""
    busy = _busy_population()
    one = busy.realize(detectors=["E1"], duration=64.0, sampling_frequency=SAMPLING_FREQUENCY, seed=1)
    other = busy.realize(detectors=["E1"], duration=64.0, sampling_frequency=SAMPLING_FREQUENCY, seed=2)
    assert not np.array_equal(one.strain["E1"], other.strain["E1"])


def test_paired_geometry_arms_share_the_realization_of_every_common_channel() -> None:
    """The invariant a two-geometry comparison is measuring against.

    Run the same population and seed over a three-interferometer network and over a
    two-interferometer one. The channels both networks contain have to carry the identical
    glitch strain, or the difference between the geometries is partly the difference
    between two random draws.
    """
    busy = _busy_population()
    triangle = busy.realize(detectors=["E1", "E2", "E3"], duration=64.0, sampling_frequency=SAMPLING_FREQUENCY, seed=5)
    pair = busy.realize(detectors=["E1", "E2"], duration=64.0, sampling_frequency=SAMPLING_FREQUENCY, seed=5)

    assert triangle.events
    for detector in ("E1", "E2"):
        assert np.array_equal(triangle.strain[detector], pair.strain[detector])


def test_paired_signal_and_noise_arms_add_the_same_glitch_array() -> None:
    """What "bit-identical glitches between the arms" means in practice.

    Two arms are built over *different* base noise and given the same seed. They have to
    inject glitch for glitch the same transients, because the glitch stream is drawn from
    its own seeded generator and knows nothing about what it is being added to. Each arm's
    strain is then its own base plus the shared realization, to the precision floating-point
    summation order allows -- and a campaign that ingests one strain file into both arms
    removes even that residual, which is why the realization is exposed as an array.
    """
    busy = _busy_population()
    detectors = ["E1", "E2"]
    duration, seed = 32.0, 808
    realization = busy.realize(detectors=detectors, duration=duration, sampling_frequency=SAMPLING_FREQUENCY, seed=seed)
    assert realization.events, "the fixture must fire events for this to say anything."

    def base_for(psd_file: str) -> ColoredNoiseSimulator:
        # Colored against an Einstein Telescope curve so the noise and the glitches are the
        # same order of magnitude. Adding a 1e-24 strain to unit-amplitude white noise would
        # round it away, and the comparison would pass for a reason unrelated to glitches.
        return ColoredNoiseSimulator(
            psd_file=psd_file,
            duration=duration,
            sampling_frequency=SAMPLING_FREQUENCY,
            detectors=detectors,
            seed=seed,
            low_frequency_cutoff=5.0,
        )

    catalogues = []
    for psd_file in ("ET_10_full_cryo_psd", "ET_15_full_cryo_psd"):
        injector = busy.build_injector(base_for(psd_file))
        arm = injector.generate(duration, SAMPLING_FREQUENCY, detectors, seed=seed)
        catalogues.append(injector.glitch_events)
        without = base_for(psd_file).generate(duration, SAMPLING_FREQUENCY, detectors, seed=seed)
        for detector in detectors:
            scale = float(np.sqrt(np.mean(np.square(arm[detector]))))
            assert scale > 0.0
            assert np.allclose(
                arm[detector],
                without[detector] + realization.strain[detector],
                rtol=0.0,
                atol=1e-12 * scale,
            )
            assert not np.array_equal(arm[detector], without[detector]), (
                "the fixture must inject glitches the base noise does not swamp."
            )

    assert catalogues[0] == catalogues[1] == realization.events


def test_the_realization_streams_to_the_same_samples_as_one_call() -> None:
    """A campaign writing segment files must get what a single call would have produced."""
    busy = _busy_population()
    detectors = ["E1", "E2"]
    whole = busy.realize(detectors=detectors, duration=64.0, sampling_frequency=SAMPLING_FREQUENCY, seed=31)

    from gwmock_noise.simulators.glitches import _ZeroNoiseSimulator

    injector = busy.build_injector(
        _ZeroNoiseSimulator(detectors=detectors, duration=16.0, sampling_frequency=SAMPLING_FREQUENCY, seed=31)
    )
    chunks: dict[str, list[np.ndarray]] = {detector: [] for detector in detectors}
    seed: int | None = 31
    for _ in range(4):
        result = injector.generate(16.0, SAMPLING_FREQUENCY, detectors, seed=seed)
        for detector in detectors:
            chunks[detector].append(result[detector])
        seed = None

    assert whole.events
    for detector in detectors:
        assert np.array_equal(np.concatenate(chunks[detector]), whole.strain[detector])


def test_the_stamp_identifies_the_population_and_the_realization(population: GlitchPopulation) -> None:
    """What a campaign manifest records so a later run can prove it used the same model."""
    realization = population.realize(
        detectors=["E1", "E2"], duration=8.0, sampling_frequency=SAMPLING_FREQUENCY, seed=77, gps_start=1e9
    )
    stamp = realization.stamp
    assert stamp["population"] == anchors.POPULATION_NAME
    assert stamp["digest"] == REGISTERED_DIGEST
    assert stamp["schema_version"] == GLITCH_POPULATION_SCHEMA_VERSION
    assert stamp["seed"] == 77
    assert stamp["detectors"] == ["E1", "E2"]
    assert stamp["gps_start"] == 1e9
    assert stamp["event_count"] == len(realization.events)
    assert stamp["gwmock_noise_version"]


# ---------------------------------------------------------------------------------------
# Empty populations and boundary values
# ---------------------------------------------------------------------------------------


def test_a_population_at_zero_rate_injects_nothing_and_says_so() -> None:
    """An empty population is a legitimate configuration, not an error.

    It is the control arm of any glitch study, so it has to produce exactly zero strain
    rather than "almost none", and its stamp has to record that it produced nothing rather
    than leaving a consumer to infer it from an absent file.
    """
    empty = et_o3_anchored_population(short_rate_hz=0.0, coherent_rate_hz=0.0)
    realization = empty.realize(detectors=["E1", "E2"], duration=64.0, sampling_frequency=SAMPLING_FREQUENCY, seed=3)

    assert realization.events == []
    assert realization.stamp["event_count"] == 0
    for strain in realization.strain.values():
        assert not np.any(strain)
    rows = empty.expected_counts(livetime_seconds=1e6, detectors=["E1", "E2"])
    assert all(row.expected == 0.0 for row in rows)
    assert empty.digest() != REGISTERED_DIGEST


def test_a_coherent_class_at_zero_participation_still_draws_its_network_events() -> None:
    """Zero participation empties the channels without emptying the process.

    The distinction matters for the decomposition: a campaign sweeping participation is
    varying how much of a fixed population reaches the instruments, not how large the
    population is.
    """
    silent = et_o3_anchored_population(short_rate_hz=0.0, coherent_rate_hz=0.5, participation_probability=0.0)
    realization = silent.realize(detectors=["E1", "E2"], duration=64.0, sampling_frequency=SAMPLING_FREQUENCY, seed=4)
    assert realization.events == []

    coherent = [
        row
        for row in silent.expected_counts(livetime_seconds=64.0, detectors=["E1", "E2"])
        if row.glitch_class == "network_coherent"
    ]
    assert len(coherent) == 2
    for row in coherent:
        assert row.expected == 0.0
        assert row.network_events == pytest.approx(0.5 * 64.0)


@pytest.mark.parametrize(
    ("threshold", "expected"),
    [(7.5, 1.0), (7.4, 1.0), (344.38, 0.0), (400.0, 0.0)],
)
def test_the_amplitude_law_survives_its_own_boundaries(threshold: float, expected: float) -> None:
    """At and below the threshold everything survives; at and above the truncation nothing does."""
    law = PowerLawSNRDistribution(
        minimum=anchors.REFERENCE_SNR_THRESHOLD,
        alpha=anchors.SHORT_SNR_ALPHA,
        maximum=anchors.SHORT_SNR_MAXIMUM,
    )
    assert law.survival(threshold) == pytest.approx(expected)


def test_the_truncated_survival_matches_what_the_sampler_draws() -> None:
    """Closed form against the generator, so the selection factor is not a separate model."""
    law = PowerLawSNRDistribution(
        minimum=anchors.REFERENCE_SNR_THRESHOLD,
        alpha=anchors.SHORT_SNR_ALPHA,
        maximum=anchors.SHORT_SNR_MAXIMUM,
    )
    rng = np.random.default_rng(404)
    draws = np.array([law.sample(rng) for _ in range(50_000)])
    assert draws.min() >= anchors.REFERENCE_SNR_THRESHOLD
    assert draws.max() <= anchors.SHORT_SNR_MAXIMUM
    for threshold in (10.0, 20.0, 50.0, 100.0):
        empirical = float(np.mean(draws >= threshold))
        assert empirical == pytest.approx(law.survival(threshold), abs=4.0 * np.sqrt(empirical / draws.size))


def test_an_untruncated_tail_survives_past_any_truncation_point() -> None:
    """The truncation is doing work, not decorating the configuration."""
    threshold, alpha = anchors.REFERENCE_SNR_THRESHOLD, anchors.SHORT_SNR_ALPHA
    untruncated = PowerLawSNRDistribution(minimum=threshold, alpha=alpha)
    truncated = PowerLawSNRDistribution(minimum=threshold, alpha=alpha, maximum=anchors.SHORT_SNR_MAXIMUM)
    assert untruncated.survival(anchors.SHORT_SNR_MAXIMUM) > 0.0
    assert truncated.survival(anchors.SHORT_SNR_MAXIMUM) == 0.0
    assert truncated.survival(50.0) < untruncated.survival(50.0)


def test_the_population_refuses_a_rate_too_low_to_represent_its_band(
    population: GlitchPopulation,
) -> None:
    """A band the Nyquist frequency cannot carry is refused rather than quietly narrowed.

    The registered short class is supported to 780 Hz, so it needs at least 1560 Hz. A run
    that narrowed it instead would inject a class that is not the registered one while
    reporting the registered digest.
    """
    with pytest.raises(ValueError, match="Nyquist"):
        population.realize(detectors=["E1"], duration=4.0, sampling_frequency=1024.0, seed=1)


def test_a_model_scoped_with_a_zero_rate_states_that_a_channel_carries_nothing() -> None:
    """The coverage rule's own escape hatch, exercised through a population.

    An interferometer no model claims is refused; an interferometer claimed by a model with
    rate zero is the supported way to say it carries no glitches, and the decomposition has
    to report that as a zero rather than omit the row.
    """
    quiet = BlipGlitch(
        rate=0.0,
        amplitude_distribution=LogNormalAmplitudeDistribution(mean=1.0, std=0.0),
        detectors=["E3"],
    )
    base = et_o3_anchored_population()
    scoped = replace(
        base,
        classes=(
            *(replace(entry, model=replace_detectors(entry.model, ["E1", "E2"])) for entry in base.classes),
            GlitchClass(
                name="quiet_channel",
                morphology="none",
                description="States that E3 carries no glitches.",
                model=quiet,
            ),
        ),
    )
    rows = scoped.expected_counts(livetime_seconds=1e5, detectors=["E1", "E2", "E3"])
    assert [(row.glitch_class, row.detector) for row in rows if row.detector == "E3"] == [("quiet_channel", "E3")]
    assert all(row.expected == 0.0 for row in rows if row.detector == "E3")
