"""ARMA / state-space noise simulator fitted from a tabulated PSD.

The simulator combines three pieces so that a tabulated detector spectrum with
lines can be generated by a bounded-state IIR filter:

* **Pole placement.** Every requested (or detected) spectral line contributes a
  conjugate pole pair at the line frequency, with a radius set by the line
  width. Those poles anchor the sharp features an all-pole fit of the same
  order cannot hold.
* **Levinson-Durbin denominator.** The target is pre-whitened by the placed
  poles and the remaining smooth part is fitted with the stable Levinson
  recursion, so the denominator is stable by construction.
* **Log-spectrum-matched numerator.** The numerator is the truncated
  minimum-phase spectral factor of the pre-whitened target, which is the
  log-spectrum matching step.

The fit exposes both orders, the state size, the conditioning diagnostics and
the relative PSD residual per band. A fit that cannot produce a finite, stable
filter raises instead of degrading.

What pole placement costs. A placed pole's peak height is fixed by its radius,
which the line width sets, and not by how far the target's line actually rises
above its surroundings. On the bundled presets, whose tabulated lines are one
to three samples wide, that makes the model spectrum overshoot at the line:
placing the single strongest line of the measured O3 Hanford curve raises the
worst band residual from 0.36 to 0.81, and placing the eight the detector
selects raises it to about 1e14, unchanged when the moving-average order is
raised from 32 to 1024. Pole placement is therefore useful for lines whose
width is known and whose contrast is modest, and the default is to place none.
``docs/dev/anchored_quantities.md`` records the measurement.
"""

from __future__ import annotations

import hashlib
import pickle
import time
from collections.abc import Iterator
from pathlib import Path
from typing import TYPE_CHECKING, Any

import numpy as np
from scipy.signal import lfilter

from gwmock_noise.simulators._fit import (
    DEFAULT_FIT_BANDS,
    FitError,
    band_fit_residual,
    levinson_durbin,
    require_nonnegative_spectrum,
    toeplitz_condition_number,
)
from gwmock_noise.simulators._spectral import load_spectral_series
from gwmock_noise.simulators.base import ConfigurableNoiseSimulator
from gwmock_noise.simulators.overlap_save import minimum_phase_from_magnitude

if TYPE_CHECKING:
    from gwmock_noise.config.models import NoiseComponentConfig, NoiseConfig

DEFAULT_AR_ORDER = 192
DEFAULT_MA_ORDER = 32
DEFAULT_BLOCK_SIZE = 65_536
DEFAULT_REGULARIZATION = 1e-10
#: Default full width of a placed spectral line, in hertz. Measured, not
#: chosen: it is the median full width at half maximum of the 94 lines the
#: bundled PSD presets tabulate, taken on the grid this fit interpolates them
#: onto. Those lines are one to three samples wide, so the number is a property
#: of the tabulated curves rather than of the detectors' physical line widths,
#: and it shifts by about 0.05 Hz with the baseline convention used to measure
#: it. ``scripts/measure_anchored_quantities.py line-width`` reproduces it and
#: ``docs/dev/anchored_quantities.md`` records the measurement.
DEFAULT_LINE_WIDTH_HZ = 0.46
DEFAULT_MAX_LINES = 8
#: Minimum peak-to-median ratio for :func:`_detect_line_frequencies`. Measured
#: against the lines the bundled presets tabulate: over those eleven curves the
#: largest peak-to-median ratio of a candidate that is *not* a tabulated line
#: is 12.18, and the weakest tabulated line standing above that floor scores
#: 18.63, so the two populations separate and this is the round value inside
#: the gap. It gives precision 1.000 and recall 0.935 at
#: :data:`DEFAULT_MAX_LINES`, against 0.750 and 0.968 at the earlier 4.0.
DEFAULT_LINE_PROMINENCE = 15.0
LINE_RADIUS_LIMIT = 0.999999
MIN_INTERPOLATION_POINTS = 2
MIN_LINE_DETECTION_POINTS = 3
RESUME_STATE_FORMAT_VERSION = 1


def _stable_detector_hash(detector: str) -> int:
    """Return a stable integer hash for a detector label."""
    digest = hashlib.blake2b(detector.encode("utf-8"), digest_size=8).digest()
    return int.from_bytes(digest, byteorder="little", signed=False)


def _line_pole_factor(frequency: float, width: float, sampling_frequency: float) -> np.ndarray:
    """Return the quadratic pole factor for one spectral line.

    A Lorentzian resonance of half-width ``width / 2`` at rate ``f_s`` sits at
    radius ``r = exp(-pi * width / f_s)``, whose impulse response decays with a
    ``1/e`` memory of ``1 / (1 - r)`` samples.

    Args:
        frequency: Line frequency in hertz.
        width: Full line width in hertz (must be positive).
        sampling_frequency: Sampling frequency in hertz.

    Returns:
        The ``[1, -2 r cos(w0), r**2]`` factor.

    Raises:
        FitError: If the width is not positive or the pole radius reaches one.
    """
    if width <= 0.0:
        raise FitError("spectral line widths must be positive.")
    radius = float(np.exp(-np.pi * width / sampling_frequency))
    if not np.isfinite(radius) or radius <= 0.0 or radius >= LINE_RADIUS_LIMIT:
        raise FitError("spectral line width places the pole on or outside the unit circle.")
    angle = 2.0 * np.pi * frequency / sampling_frequency
    return np.array([1.0, -2.0 * radius * np.cos(angle), radius**2], dtype=float)


def _log_spectrum_numerator(
    residual_spectrum: np.ndarray,
    angular_frequencies: np.ndarray,
    order: int,
) -> np.ndarray:
    """Fit a minimum-phase numerator by matching the log spectrum.

    The logarithm of a positive spectrum is a cosine series whose coefficients
    are the cepstrum of the minimum-phase spectral factor. Fitting that series
    over the fitted band with least squares and factoring the *fitted* log
    magnitude with the cepstral method gives the truncated numerator, which is
    exactly log-spectrum matching.

    Args:
        residual_spectrum: Residual spectrum on the design grid.
        angular_frequencies: Angular frequencies of the design grid.
        order: Moving-average order ``q``.

    Returns:
        The ``q + 1`` numerator taps.

    Raises:
        FitError: If the residual has no positive samples or a non-finite fit.
    """
    positive = (residual_spectrum > 0.0) & np.isfinite(residual_spectrum)
    if not np.any(positive):
        raise FitError("The target has no usable spectral content for the numerator fit.")
    log_spectrum = np.log(residual_spectrum[positive])
    frequencies = angular_frequencies[positive]
    design = np.stack(
        [np.ones_like(frequencies)] + [2.0 * np.cos(frequencies * index) for index in range(1, order + 1)],
        axis=1,
    )
    coefficients, *_ = np.linalg.lstsq(design, log_spectrum, rcond=None)
    if not np.all(np.isfinite(coefficients)):
        raise FitError("Fitted ARMA log-spectrum coefficients are not finite.")

    fitted_log_magnitude = coefficients[0] / 2.0 + sum(
        coefficients[index] * np.cos(angular_frequencies * index) for index in range(1, order + 1)
    )
    # The cosine series is only fitted inside the band; outside it can diverge,
    # so bound it to the range it was fitted over before exponentiating. This
    # keeps the out-of-band extrapolation finite without touching the fit.
    fitted_log_magnitude = np.clip(fitted_log_magnitude, float(np.min(log_spectrum)), float(np.max(log_spectrum)))
    if not np.all(np.isfinite(fitted_log_magnitude)):
        raise FitError("Fitted ARMA log-spectrum magnitude is not finite.")
    full_numerator = minimum_phase_from_magnitude(np.exp(fitted_log_magnitude))
    numerator = np.asarray(full_numerator[: order + 1], dtype=float)
    if not np.all(np.isfinite(numerator)):
        raise FitError("Fitted ARMA numerator is not finite.")
    return numerator


def _detect_line_frequencies(
    frequencies: np.ndarray,
    values: np.ndarray,
    *,
    max_lines: int,
    prominence: float,
) -> list[float]:
    """Return the most prominent local maxima of a PSD.

    The ratio is taken against the median of the whole fitted band, so it is
    not a local prominence: on a target whose baseline varies by orders of
    magnitude across the band, ripple sitting on the steep low-frequency rise
    scores as highly as a narrow line sitting on the flat mid-band floor, and
    the same feature scores differently when the band edges move. The default
    threshold is measured at the full band up to the Nyquist frequency; over a
    narrower band it does not carry the precision quoted for it.

    Args:
        frequencies: Strictly increasing frequency grid.
        values: PSD values on the grid.
        max_lines: Maximum number of lines to return.
        prominence: Minimum peak-to-median ratio for a local maximum.

    Returns:
        The selected line frequencies, in increasing order.
    """
    if frequencies.size < MIN_LINE_DETECTION_POINTS or max_lines < 1:
        return []
    candidate_mask = (values[1:-1] >= values[:-2]) & (values[1:-1] > values[2:])
    candidate_indices = np.flatnonzero(candidate_mask) + 1
    if candidate_indices.size == 0:
        return []
    baseline = float(np.median(values))
    if baseline <= 0.0:
        return []
    ratios = values[candidate_indices] / baseline
    accepted = candidate_indices[ratios >= prominence]
    if accepted.size == 0:
        return []
    order = np.argsort(values[accepted])[::-1][:max_lines]
    return sorted({float(frequencies[index]) for index in accepted[order]})


class ARMANoiseSimulator(ConfigurableNoiseSimulator):
    """Generate stationary detector noise with a fitted ARMA / state-space model."""

    simulator_name = "arma"

    def __init__(  # noqa: PLR0913, PLR0915
        self,
        *,
        psd_file: str | Path | None = None,
        target_psd: np.ndarray | None = None,
        target_frequencies: np.ndarray | None = None,
        ar_order: int = DEFAULT_AR_ORDER,
        ma_order: int = DEFAULT_MA_ORDER,
        line_frequencies: list[float] | None = None,
        line_widths: list[float] | None = None,
        detect_lines: bool = False,
        max_lines: int = DEFAULT_MAX_LINES,
        line_prominence: float = DEFAULT_LINE_PROMINENCE,
        detectors: list[str] | None = None,
        sampling_frequency: float = 4096.0,
        duration: float = 4.0,
        seed: int | None = None,
        low_frequency_cutoff: float = 2.0,
        high_frequency_cutoff: float | None = None,
        block_size: int = DEFAULT_BLOCK_SIZE,
        regularization: float = DEFAULT_REGULARIZATION,
    ) -> None:
        """Initialize the simulator and fit the ARMA model once.

        Args:
            psd_file: Path or bundled preset name of a two-column PSD table.
            target_psd: One-sided target PSD array, mutually exclusive with
                ``psd_file``.
            target_frequencies: Frequencies of ``target_psd`` in hertz.
            ar_order: Autoregressive order ``p`` of the denominator.
            ma_order: Moving-average order ``q`` of the numerator.
            line_frequencies: Explicit line frequencies to place poles at.
            line_widths: Widths matching ``line_frequencies``; defaults to
                :data:`DEFAULT_LINE_WIDTH_HZ`.
            detect_lines: Whether to detect prominent lines from the target.
            max_lines: Maximum number of detected lines.
            line_prominence: Minimum peak-to-median ratio for detection.
            detectors: Detector names to generate.
            sampling_frequency: Sampling frequency in hertz.
            duration: Nominal generation duration in seconds.
            seed: Base seed for the per-detector generators.
            low_frequency_cutoff: Lower edge of the target band in hertz.
            high_frequency_cutoff: Upper edge of the target band in hertz.
            block_size: Number of samples generated per filter call.
            regularization: Relative ridge added to the zero-lag autocovariance.
        """
        if (psd_file is None) == (target_psd is None):
            raise ValueError("Exactly one of psd_file or target_psd must be provided.")
        if ar_order < 0 or ma_order < 0:
            raise ValueError("ar_order and ma_order must be non-negative.")
        if ar_order == 0 and ma_order == 0:
            raise ValueError("at least one of ar_order or ma_order must be positive.")
        if block_size < 1:
            raise ValueError("block_size must be a positive integer.")
        if regularization < 0.0:
            raise ValueError("regularization must be non-negative.")

        self.psd_file = Path(psd_file) if psd_file is not None else None
        self.ar_order = ar_order
        self.ma_order = ma_order
        self.line_frequencies = list(line_frequencies) if line_frequencies is not None else []
        self.line_widths = list(line_widths) if line_widths is not None else []
        self.detect_lines = detect_lines
        self.max_lines = max_lines
        self.line_prominence = line_prominence
        self.detectors = list(detectors) if detectors is not None else ["H1", "L1"]
        self.sampling_frequency = sampling_frequency
        self.duration = duration
        self.seed = seed
        self.low_frequency_cutoff = low_frequency_cutoff
        self.high_frequency_cutoff = high_frequency_cutoff
        self.block_size = block_size
        self.regularization = regularization

        if len(self.line_widths) not in {0, len(self.line_frequencies)}:
            raise ValueError("line_widths must be empty or match line_frequencies in length.")
        if not all(np.isfinite(self.line_frequencies)):
            raise ValueError("line_frequencies must be finite.")

        self._validate_runtime(duration=duration, sampling_frequency=sampling_frequency, detectors=self.detectors)

        self._rngs: dict[str, np.random.Generator] = {}
        self._filter_state: dict[str, np.ndarray] = {}
        self._denominator_coefficients = np.ones(1, dtype=float)
        self._numerator_coefficients = np.ones(1, dtype=float)
        self._innovation_variance = 0.0
        self._sigma_squared = 0.0
        self._fit_time_seconds = 0.0
        self._fit_grid_size = 0
        self._high_frequency_cutoff = 0.0
        self._reflection_coefficients = np.zeros(0, dtype=float)
        self._prediction_errors = np.zeros(1, dtype=float)
        self._condition_number = 1.0
        self._placed_lines: list[dict[str, float]] = []
        self._state_size = 0
        self._target_frequencies = np.zeros(0, dtype=float)
        self._target_psd = np.zeros(0, dtype=float)
        self._model_psd = np.zeros(0, dtype=float)
        self._band_mask = np.zeros(0, dtype=bool)
        self._fit_residual: dict[str, object] = {
            "band_count": 0,
            "worst_relative_error": 0.0,
            "median_relative_error": 0.0,
            "bands": [],
        }

        self._source_frequencies: np.ndarray | None = None
        self._source_values: np.ndarray | None = None
        if target_psd is not None:
            self._source_frequencies, self._source_values = self._resolve_array_target(target_psd, target_frequencies)

        self._fit_model()

    @classmethod
    def from_component(cls, component: NoiseComponentConfig, config: NoiseConfig) -> ARMANoiseSimulator:
        """Construct an ARMA simulator from one component definition."""
        options = dict(component.options)
        psd_file = options.pop("psd_file", None)
        target_psd = options.pop("target_psd", None)
        if psd_file is None and target_psd is None:
            raise ValueError("ARMA simulator requires 'psd_file' or 'target_psd' in the component options.")
        return cls(
            psd_file=psd_file,
            target_psd=target_psd,
            detectors=config.detectors,
            duration=config.duration,
            sampling_frequency=config.sampling_frequency,
            seed=config.seed,
            **options,
        )

    def _resolve_array_target(
        self,
        target_psd: np.ndarray,
        target_frequencies: np.ndarray | None,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Normalize an array target into sorted ``(frequencies, values)``."""
        values = np.asarray(target_psd, dtype=float)
        if values.ndim != 1 or values.size < MIN_INTERPOLATION_POINTS:
            raise ValueError("target_psd must be a one-dimensional array with at least two samples.")
        if not np.all(np.isfinite(values)):
            raise FitError("target_psd must be finite.")
        if target_frequencies is None:
            frequencies = np.fft.rfftfreq(2 * (values.size - 1), d=1.0 / self.sampling_frequency)
            return frequencies, values
        frequencies = np.asarray(target_frequencies, dtype=float)
        if frequencies.shape != values.shape:
            raise ValueError("target_frequencies and target_psd must have the same length.")
        if not np.all(np.diff(frequencies) > 0.0):
            raise ValueError("target_frequencies must be strictly increasing.")
        return frequencies, values

    def _validate_runtime(
        self,
        *,
        duration: float,
        sampling_frequency: float,
        detectors: list[str],
    ) -> None:
        """Validate runtime arguments shared by initialization and generation."""
        if duration <= 0:
            raise ValueError("duration must be greater than zero.")
        if sampling_frequency <= 0:
            raise ValueError("sampling_frequency must be greater than zero.")
        if not detectors:
            raise ValueError("detectors must contain at least one detector.")
        if len(set(detectors)) != len(detectors):
            raise ValueError("detectors must not contain duplicate names.")
        if self.low_frequency_cutoff < 0:
            raise ValueError("low_frequency_cutoff must be non-negative.")

        nyquist = sampling_frequency / 2.0
        high_frequency_cutoff = self.high_frequency_cutoff if self.high_frequency_cutoff is not None else nyquist
        if high_frequency_cutoff <= self.low_frequency_cutoff:
            raise ValueError("high_frequency_cutoff must be greater than low_frequency_cutoff.")
        if high_frequency_cutoff > nyquist:
            raise ValueError("high_frequency_cutoff must not exceed the Nyquist frequency.")

    def _resolve_lines(self, frequencies: np.ndarray, values: np.ndarray) -> list[tuple[float, float]]:
        """Return the ``(frequency, width)`` pairs to place poles at."""
        detected = (
            _detect_line_frequencies(
                frequencies,
                values,
                max_lines=self.max_lines,
                prominence=self.line_prominence,
            )
            if self.detect_lines and not self.line_frequencies
            else []
        )
        resolved: list[tuple[float, float]] = []
        for index, frequency in enumerate(self.line_frequencies):
            width = self.line_widths[index] if self.line_widths else DEFAULT_LINE_WIDTH_HZ
            resolved.append((float(frequency), float(width)))
        for frequency in detected:
            resolved.append((float(frequency), float(DEFAULT_LINE_WIDTH_HZ)))
        return resolved

    def _fit_model(self) -> None:  # noqa: PLR0915
        """Fit the pole-placement + Levinson denominator and the matched numerator."""
        fit_start = time.perf_counter()

        if self.psd_file is not None:
            source_frequencies, source_values = load_spectral_series(self.psd_file, kind="PSD")
        else:
            if (
                self._source_frequencies is None or self._source_values is None
            ):  # pragma: no cover - guarded by __init__
                raise FitError("No target spectrum is available to fit.")
            source_frequencies, source_values = self._source_frequencies, self._source_values

        self._fit_grid_size = max(
            2 * (source_frequencies.size - 1),
            8 * max(self.ar_order, self.ma_order + 1),
        )
        nyquist = self.sampling_frequency / 2.0
        self._high_frequency_cutoff = self.high_frequency_cutoff if self.high_frequency_cutoff is not None else nyquist

        frequency_grid = np.fft.rfftfreq(self._fit_grid_size, d=1.0 / self.sampling_frequency)
        frequency_mask = (frequency_grid >= self.low_frequency_cutoff) & (frequency_grid <= self._high_frequency_cutoff)
        if not np.any(frequency_mask):
            raise ValueError("The requested frequency range contains no simulation bins.")

        interpolated = np.interp(frequency_grid[frequency_mask], source_frequencies, source_values, left=0.0, right=0.0)
        require_nonnegative_spectrum(interpolated, label="target PSD")
        target_psd = np.zeros_like(frequency_grid, dtype=float)
        target_psd[frequency_mask] = interpolated
        self._target_frequencies = frequency_grid
        self._target_psd = target_psd
        self._band_mask = frequency_mask

        angular_frequencies = 2.0 * np.pi * frequency_grid / self.sampling_frequency
        lines = self._resolve_lines(frequency_grid[frequency_mask], target_psd[frequency_mask])

        pole_denominator = np.ones(1, dtype=float)
        self._placed_lines = []
        for frequency, width in lines:
            if frequency <= self.low_frequency_cutoff or frequency >= self._high_frequency_cutoff:
                raise FitError("spectral line frequency lies outside the fitted band.")
            factor = _line_pole_factor(frequency, width, self.sampling_frequency)
            pole_denominator = np.convolve(pole_denominator, factor)
            self._placed_lines.append(
                {"frequency": float(frequency), "width": float(width), "radius": float(np.sqrt(factor[-1]))}
            )

        pole_response = np.polyval(pole_denominator[::-1], np.exp(-1j * angular_frequencies))
        prewhitened = target_psd * np.abs(pole_response) ** 2

        autocovariance = np.fft.irfft(prewhitened * self.sampling_frequency / 2.0, n=self._fit_grid_size)
        autocovariance = np.asarray(autocovariance[: self.ar_order + 1], dtype=float)
        if autocovariance[0] <= 0.0:
            raise FitError("Target PSD integrates to zero variance in the requested band.")
        if self.regularization > 0.0:
            autocovariance[0] *= 1.0 + self.regularization

        fit = levinson_durbin(autocovariance, self.ar_order)
        self._reflection_coefficients = np.asarray(fit.reflection_coefficients, dtype=float)
        self._prediction_errors = np.asarray(fit.prediction_errors, dtype=float)
        self._condition_number = toeplitz_condition_number(autocovariance[:-1], self.ar_order) if self.ar_order else 1.0
        self._denominator_coefficients = np.convolve(
            pole_denominator,
            np.concatenate(([1.0], np.asarray(fit.coefficients, dtype=float))),
        )

        denominator_response = np.polyval(self._denominator_coefficients[::-1], np.exp(-1j * angular_frequencies))
        residual_spectrum = (self.sampling_frequency / 2.0) * target_psd * np.abs(denominator_response) ** 2
        self._numerator_coefficients = _log_spectrum_numerator(
            residual_spectrum,
            angular_frequencies,
            self.ma_order,
        )

        # SciPy's direct-form II filter carries ``max(len(b), len(a)) - 1`` delay
        # elements, which grows by two per placed conjugate pole pair. That is
        # the continuation state this simulator records and serialises.
        self._state_size = int(max(self._numerator_coefficients.size, self._denominator_coefficients.size) - 1)
        base_spectrum = self._evaluate_model_spectrum()
        positive = target_psd > 0.0
        log_ratio = np.log(target_psd[positive]) - np.log(base_spectrum[positive])
        self._sigma_squared = float(np.exp(np.mean(log_ratio)))
        if not np.isfinite(self._sigma_squared) or self._sigma_squared <= 0.0:
            raise FitError("Fitted ARMA innovation variance is not positive.")
        self._innovation_variance = self._sigma_squared
        self._model_psd = self._sigma_squared * base_spectrum
        self._fit_residual = band_fit_residual(
            frequency_grid[frequency_mask],
            target_psd[frequency_mask],
            self._model_psd[frequency_mask],
            low_frequency=self.low_frequency_cutoff,
            high_frequency=self._high_frequency_cutoff,
            n_bands=DEFAULT_FIT_BANDS,
        )

        self._fit_time_seconds = time.perf_counter() - fit_start
        self._filter_state = {detector: np.zeros(max(self._state_size, 0), dtype=float) for detector in self.detectors}

    def _evaluate_model_spectrum(self) -> np.ndarray:
        """Return ``2 |B / A|^2 / f_s`` on the design grid via the impulse response."""
        impulse = np.zeros(self._fit_grid_size, dtype=float)
        impulse[0] = 1.0
        response = np.fft.rfft(
            lfilter(self._numerator_coefficients, self._denominator_coefficients, impulse),
            n=self._fit_grid_size,
        )
        return (2.0 / self.sampling_frequency) * np.abs(response) ** 2

    def _initialize_generators(self, seed: int | None) -> None:
        """Initialize one RNG per detector."""
        if seed is None:
            seed_sequence = np.random.SeedSequence()
            child_sequences = seed_sequence.spawn(len(self.detectors))
        else:
            child_sequences = [
                np.random.SeedSequence([seed, _stable_detector_hash(detector)]) for detector in self.detectors
            ]
        self._rngs = {
            detector: np.random.default_rng(child_sequence)
            for detector, child_sequence in zip(self.detectors, child_sequences, strict=True)
        }

    def _generate_block(self, detector: str, n_samples: int) -> np.ndarray:
        """Generate one contiguous ARMA block for a single detector."""
        innovations = self._rngs[detector].standard_normal(n_samples) * np.sqrt(self._sigma_squared)
        strain, filter_state = lfilter(
            self._numerator_coefficients,
            self._denominator_coefficients,
            innovations,
            zi=self._filter_state[detector],
        )
        self._filter_state[detector] = filter_state
        return strain

    def reset(self) -> None:
        """Clear filter state and RNGs."""
        self._rngs = {}
        self._filter_state = {detector: np.zeros(max(self._state_size, 0), dtype=float) for detector in self.detectors}

    def generate(
        self,
        duration: float,
        sampling_frequency: float,
        detectors: list[str],
        seed: int | None = None,
    ) -> dict[str, np.ndarray]:
        """Generate per-detector ARMA noise with continuity across calls."""
        runtime_detectors = list(detectors)
        self._validate_runtime(
            duration=duration,
            sampling_frequency=sampling_frequency,
            detectors=runtime_detectors,
        )

        runtime_changed = (
            sampling_frequency != self.sampling_frequency
            or runtime_detectors != self.detectors
            or self._high_frequency_cutoff
            != (self.high_frequency_cutoff if self.high_frequency_cutoff is not None else sampling_frequency / 2.0)
        )

        self.duration = duration
        self.sampling_frequency = sampling_frequency
        self.detectors = runtime_detectors

        if runtime_changed:
            self._fit_model()
            self.reset()

        if seed is not None:
            self.seed = seed
            self.reset()

        if not self._rngs:
            self._initialize_generators(self.seed)

        n_samples = round(duration * sampling_frequency)
        if n_samples < 1:
            raise ValueError("duration and sampling_frequency must produce at least one sample.")

        realizations: dict[str, np.ndarray] = {}
        for detector in self.detectors:
            blocks = []
            remaining = n_samples
            while remaining > 0:
                chunk_size = min(self.block_size, remaining)
                blocks.append(self._generate_block(detector, chunk_size))
                remaining -= chunk_size
            realizations[detector] = np.concatenate(blocks) if len(blocks) > 1 else blocks[0]
        return realizations

    def generate_stream(
        self,
        chunk_duration: float,
        sampling_frequency: float,
        detectors: list[str],
        seed: int | None = None,
    ) -> Iterator[dict[str, np.ndarray]]:
        """Yield ARMA chunks lazily while preserving filter state."""
        while True:
            yield self.generate(chunk_duration, sampling_frequency, detectors, seed)
            seed = None

    def continuation_state(self) -> dict[str, Any]:
        """Return the bounded state needed to keep a running stream going."""
        return {
            "format_version": RESUME_STATE_FORMAT_VERSION,
            "filter_state": {detector: state.copy() for detector, state in self._filter_state.items()},
        }

    def resume_metadata(self) -> dict[str, Any]:
        """Return the metadata a stopped stream must persist to resume."""
        return {
            "format_version": RESUME_STATE_FORMAT_VERSION,
            "ar_order": self.ar_order,
            "ma_order": self.ma_order,
            "detectors": list(self.detectors),
            "sampling_frequency": self.sampling_frequency,
            "seed": self.seed,
            "rng_state": {detector: rng.bit_generator.state for detector, rng in self._rngs.items()},
        }

    def export_state(self) -> dict[str, Any]:
        """Return a picklable snapshot sufficient to resume the stream."""
        return {"continuation": self.continuation_state(), "resume": self.resume_metadata()}

    def import_state(self, state: dict[str, Any]) -> None:
        """Restore a snapshot produced by :meth:`export_state`.

        Args:
            state: A snapshot from another simulator with the same configuration.

        Raises:
            ValueError: If the snapshot does not match this simulator's settings.
        """
        continuation = state["continuation"]
        resume = state["resume"]
        if resume["ar_order"] != self.ar_order or resume["ma_order"] != self.ma_order:
            raise ValueError("resume metadata orders do not match this simulator.")
        if resume["detectors"] != self.detectors:
            raise ValueError("resume metadata detectors do not match this simulator.")
        if resume["sampling_frequency"] != self.sampling_frequency:
            raise ValueError("resume metadata sampling frequency does not match this simulator.")

        self.seed = resume["seed"]
        self._initialize_generators(self.seed)
        for detector, rng_state in resume["rng_state"].items():
            self._rngs[detector].bit_generator.state = rng_state
        for detector in self.detectors:
            self._filter_state[detector] = np.asarray(continuation["filter_state"][detector], dtype=float).copy()

    @property
    def denominator_coefficients(self) -> np.ndarray:
        """Return a copy of the ARMA denominator coefficients ``a_1 .. a_p``."""
        return self._denominator_coefficients[1:].copy()

    @property
    def numerator_coefficients(self) -> np.ndarray:
        """Return a copy of the ARMA numerator coefficients ``b_0 .. b_q``."""
        return self._numerator_coefficients.copy()

    @property
    def target_psd_curve(self) -> tuple[np.ndarray, np.ndarray]:
        """Return the band-masked target PSD on the design grid."""
        return self._target_frequencies[self._band_mask], self._target_psd[self._band_mask]

    @property
    def model_psd_curve(self) -> np.ndarray:
        """Return the fitted model PSD on the band-masked design grid."""
        return self._model_psd[self._band_mask]

    @property
    def state_nbytes(self) -> int:
        """Serialized size of the continuation state in bytes."""
        return len(pickle.dumps(self.continuation_state()))

    @property
    def resume_metadata_nbytes(self) -> int:
        """Serialized size of the resume metadata in bytes."""
        return len(pickle.dumps(self.resume_metadata()))

    @property
    def metadata(self) -> dict[str, Any]:
        """Return metadata describing the fitted ARMA model."""
        return {
            "implementation": "autoregressive_moving_average",
            "duration": self.duration,
            "sampling_frequency": self.sampling_frequency,
            "detectors": list(self.detectors),
            "seed": self.seed,
            "autoregressive_moving_average": {
                "psd_file": str(self.psd_file) if self.psd_file is not None else None,
                "fit_method": "pole-placement-log-spectrum-matching",
                "ar_order": self.ar_order,
                "ma_order": self.ma_order,
                "state_size": self._state_size,
                "state_bytes": self.state_nbytes,
                "resume_metadata_bytes": self.resume_metadata_nbytes,
                "low_frequency_cutoff": self.low_frequency_cutoff,
                "high_frequency_cutoff": self._high_frequency_cutoff,
                "block_size": self.block_size,
                "fit_grid_size": self._fit_grid_size,
                "fit_time_seconds": self._fit_time_seconds,
                "regularization": self.regularization,
                "innovation_variance": self._innovation_variance,
                "placed_lines": list(self._placed_lines),
                "conditioning": {
                    "max_reflection_coefficient": float(np.max(np.abs(self._reflection_coefficients), initial=0.0)),
                    "max_reflection_limit": 1.0,
                    "min_prediction_error": float(np.min(self._prediction_errors)),
                    "toeplitz_condition_number": self._condition_number,
                    "max_placed_pole_radius": float(max((line["radius"] for line in self._placed_lines), default=0.0)),
                },
                "fit_residual": self._fit_residual,
            },
        }


__all__ = ["ARMANoiseSimulator", "FitError"]
